# Generated by Django 3.2.9 on 2025-12-11 19:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccounttype',
            options={'verbose_name': 'نوع حساب بنكي', 'verbose_name_plural': 'أنواع الحسابات البنكية'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'مستخدم', 'verbose_name_plural': 'المستخدمين'},
        ),
        migrations.AlterModelOptions(
            name='useraddress',
            options={'verbose_name': 'عنوان مستخدم', 'verbose_name_plural': 'عناوين المستخدمين'},
        ),
        migrations.AlterModelOptions(
            name='userbankaccount',
            options={'verbose_name': 'حساب بنكي', 'verbose_name_plural': 'الحسابات البنكية'},
        ),
        migrations.AlterField(
            model_name='bankaccounttype',
            name='annual_interest_rate',
            field=models.DecimalField(decimal_places=2, help_text='معدل الفائدة السنوي من 0 إلى 100', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='معدل الفائدة السنوي'),
        ),
        migrations.AlterField(
            model_name='bankaccounttype',
            name='interest_calculation_per_year',
            field=models.PositiveSmallIntegerField(help_text='عدد مرات حساب الفائدة في السنة', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='عدد مرات حساب الفائدة سنوياً'),
        ),
        migrations.AlterField(
            model_name='bankaccounttype',
            name='maximum_withdrawal_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الحد الأقصى للسحب'),
        ),
        migrations.AlterField(
            model_name='bankaccounttype',
            name='name',
            field=models.CharField(max_length=128, verbose_name='اسم نوع الحساب'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='city',
            field=models.CharField(max_length=256, verbose_name='المدينة'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='country',
            field=models.CharField(max_length=256, verbose_name='البلد'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='postal_code',
            field=models.PositiveIntegerField(verbose_name='الرمز البريدي'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='street_address',
            field=models.CharField(max_length=512, verbose_name='عنوان الشارع'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='userbankaccount',
            name='account_no',
            field=models.PositiveIntegerField(unique=True, verbose_name='رقم الحساب'),
        ),
        migrations.AlterField(
            model_name='userbankaccount',
            name='account_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='accounts.bankaccounttype', verbose_name='نوع الحساب'),
        ),
        migrations.AlterField(
            model_name='userbankaccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الرصيد'),
        ),
        migrations.AlterField(
            model_name='userbankaccount',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد'),
        ),
        migrations.AlterField(
            model_name='userbankaccount',
            name='gender',
            field=models.CharField(choices=[('M', 'ذكر'), ('F', 'أنثى')], max_length=1, verbose_name='الجنس'),
        ),
        migrations.AlterField(
            model_name='userbankaccount',
            name='initial_deposit_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ أول إيداع'),
        ),
        migrations.AlterField(
            model_name='userbankaccount',
            name='interest_start_date',
            field=models.DateField(blank=True, help_text='تاريخ بداية حساب الفائدة', null=True, verbose_name='تاريخ بداية الفائدة'),
        ),
        migrations.AlterField(
            model_name='userbankaccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
    ]
