# Generated by Django 3.2.9 on 2025-12-11 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20251211_2113'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['timestamp'], 'verbose_name': 'معاملة مالية', 'verbose_name_plural': 'المعاملات المالية'},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.userbankaccount', verbose_name='الحساب'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='balance_after_transaction',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الرصيد بعد المعاملة'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='وقت المعاملة'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'إيداع'), (2, 'سحب'), (3, 'فائدة')], verbose_name='نوع المعاملة'),
        ),
    ]
